# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GoToXYZ
                                 A QGIS plugin
 Create a polygon on XYZ bbox
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-02
        copyright            : (C) 2020 by Guillaume Hormière
        email                : hormiere.guillaume@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GoToXYZ class from file GoToXYZ.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .go_to_xyz import GoToXYZ
    return GoToXYZ(iface)
